const ngos = [
  {
      id: '1',
      name: 'Helping Hands',
      image: '/images/poorChildren.jpg',
      description: 'Providing essential resources to underprivileged communities, focusing on basic needs like food, shelter, and education.',
      location: 'Mumbai, India',
      founded: '2005',
      category: 'Community Development',
      email: 'contact@helpinghands.org',
      phone: '+91 9876543210',
      website: 'https://www.helpinghands.org',
      rating: 4.5,
  },
  {
      id: '2',
      name: 'Green Earth',
      image: '/images/Environmental Conservation.jpg',
      description: 'Dedicated to environmental protection and sustainability, working on projects like tree planting, pollution control, and wildlife conservation.',
      location: 'Bangalore, India',
      founded: '2010',
      category: 'Environmental Conservation',
      email: 'info@greenearth.org',
      phone: '+91 9876543211',
      website: 'https://www.greenearth.org',
      rating: 4.7,
  },
  {
      id: '3',
      name: 'Education for All',
      image: '/images/education.jpg',
      description: 'Empowering children through access to quality education, providing scholarships, building schools, and training teachers in rural areas.',
      location: 'Delhi, India',
      founded: '2008',
      category: 'Education',
      email: 'support@educationforall.org',
      phone: '+91 9876543212',
      website: 'https://www.educationforall.org',
      rating: 4.8,
  },
  {
      id: '4',
      name: 'Senior Citizens Care',
      image: '/images/seniorCitizens.jpg',
      description: 'Providing support, healthcare, and companionship to senior citizens, ensuring they live with dignity and comfort.',
      location: 'Chennai, India',
      founded: '2007',
      category: 'Elder Care',
      email: 'care@seniorcitizens.org',
      phone: '+91 9876543213',
      website: 'https://www.seniorcitizens.org',
      rating: 4.8,
  },
  {
      id: '5',
      name: 'Women Empowerment Foundation',
      image: '/images/woman.png',
      description: 'Promoting gender equality and supporting women\'s rights through education, legal aid, and entrepreneurship programs.',
      location: 'Kolkata, India',
      founded: '2012',
      category: 'Women\'s Rights',
      email: 'empower@womenfoundation.org',
      phone: '+91 9876543214',
      website: 'https://www.womenfoundation.org',
      rating: 4.8,
  },
  {
      id: '6',
      name: 'Animal Welfare Society',
      image: '/images/AnimalWelfare.jpg',
      description: 'Supporting and protecting animal rights through rescue operations, veterinary care, and public awareness campaigns.',
      location: 'Pune, India',
      founded: '2011',
      category: 'Animal Welfare',
      email: 'help@animalwelfare.org',
      phone: '+91 9876543215',
      website: 'https://www.animalwelfare.org',
      rating: 4.8,
  },
  {
      id: '7',
      name: 'Health and Wellness Foundation',
      image: '/images/health.jpg',
      description: 'Fostering healthy communities by providing medical care, health education, and promoting wellness initiatives.',
      location: 'Hyderabad, India',
      founded: '2009',
      category: 'Healthcare',
      email: 'health@wellnessfoundation.org',
      phone: '+91 9876543216',
      website: 'https://www.wellnessfoundation.org',
      rating: 4.7,
  },
  {
      id: '8',
      name: 'Disaster Relief Network',
      image: '/images/disaster.jpg',
      description: 'Responding to natural disasters by providing immediate relief, medical aid, and long-term recovery support to affected communities.',
      location: 'Guwahati, India',
      founded: '2006',
      category: 'Disaster Relief',
      email: 'relief@disasternetwork.org',
      phone: '+91 9876543217',
      website: 'https://www.disasternetwork.org',
      rating: 4.6,
  },
  {
      id: '9',
      name: 'Youth Development Alliance',
      image: '/images/youth.jpg',
      description: 'Supporting young people through education, mentorship, and leadership programs, aiming to empower the next generation.',
      location: 'Jaipur, India',
      founded: '2013',
      category: 'Youth Development',
      email: 'youth@developmentalliance.org',
      phone: '+91 9876543218',
      website: 'https://www.developmentalliance.org',
      rating: 4.8,
  },
  {
      id: '10',
      name: 'Global Hunger Project',
      image: '/images/hunger.jpg',
      description: 'Fighting hunger and malnutrition by delivering food, clean water, and resources to those in need, particularly in underserved regions.',
      location: 'Ahmedabad, India',
      founded: '2014',
      category: 'Hunger Relief',
      email: 'help@hungerproject.org',
      phone: '+91 9876543219',
      website: 'https://www.hungerproject.org',
      rating: 4.7,
  }
];

export default ngos;
